// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxGNfz280ExTDmwu2wzd2yWXS-8yOhY4c',
    appId: '1:614731977741:web:e13dc53d5f6902e72e7144',
    messagingSenderId: '614731977741',
    projectId: 'foodpanzu',
    authDomain: 'foodpanzu.firebaseapp.com',
    storageBucket: 'foodpanzu.appspot.com',
    measurementId: 'G-614WTS6F8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRVslXf1oFnEvRRTYtFcubYhbytmwElA',
    appId: '1:614731977741:android:5cef113aaa143b5b2e7144',
    messagingSenderId: '614731977741',
    projectId: 'foodpanzu',
    storageBucket: 'foodpanzu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-AvTbfJYOC0Vydb3zxj68aNAk-QnA20E',
    appId: '1:614731977741:ios:78fdf3c090860ff32e7144',
    messagingSenderId: '614731977741',
    projectId: 'foodpanzu',
    storageBucket: 'foodpanzu.appspot.com',
    iosClientId: '614731977741-pfq3fmmkdoq7chiehnca8iiicd5n0g5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpanzu',
  );
}
